// Copyright 2012 Google Inc
//
// The content of this file is licensed under the Creative Commons Attribution
// 3.0 License.
//
// Protocol definition OneBusAway-specific extensions to GTFS-realtime.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.3
// source: gtfs-realtime-OneBusAway.proto

package transit_realtime

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OneBusAwayFeedHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// For an incremental feed, the index of the current incremental FeedMessage.
	// Each incremental FeedMessage sent to a client should sequentially
	// increment the index, such that a client can detect missed messages by
	// looking for gaps in the index value.  It is not required that the index
	// of the first message sent to a client be zero.
	IncrementalIndex *uint64 `protobuf:"varint,1,opt,name=incremental_index,json=incrementalIndex" json:"incremental_index,omitempty"`
	// For an incremental feed, the maximum amount of time, in seconds, between
	// incremental updates.  Clients that have not received a FeedMessage, empty
	// or otherwise, in the specified time interval should assume that the
	// connection has been lost and reconnect.
	IncrementalHeartbeatInterval *uint32 `protobuf:"varint,2,opt,name=incremental_heartbeat_interval,json=incrementalHeartbeatInterval" json:"incremental_heartbeat_interval,omitempty"`
}

func (x *OneBusAwayFeedHeader) Reset() {
	*x = OneBusAwayFeedHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gtfs_realtime_OneBusAway_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OneBusAwayFeedHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneBusAwayFeedHeader) ProtoMessage() {}

func (x *OneBusAwayFeedHeader) ProtoReflect() protoreflect.Message {
	mi := &file_gtfs_realtime_OneBusAway_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneBusAwayFeedHeader.ProtoReflect.Descriptor instead.
func (*OneBusAwayFeedHeader) Descriptor() ([]byte, []int) {
	return file_gtfs_realtime_OneBusAway_proto_rawDescGZIP(), []int{0}
}

func (x *OneBusAwayFeedHeader) GetIncrementalIndex() uint64 {
	if x != nil && x.IncrementalIndex != nil {
		return *x.IncrementalIndex
	}
	return 0
}

func (x *OneBusAwayFeedHeader) GetIncrementalHeartbeatInterval() uint32 {
	if x != nil && x.IncrementalHeartbeatInterval != nil {
		return *x.IncrementalHeartbeatInterval
	}
	return 0
}

type OneBusAwayFeedEntity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Optional description of the source of a particular feed entity.
	Source *string `protobuf:"bytes,1,opt,name=source" json:"source,omitempty"`
}

func (x *OneBusAwayFeedEntity) Reset() {
	*x = OneBusAwayFeedEntity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gtfs_realtime_OneBusAway_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OneBusAwayFeedEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneBusAwayFeedEntity) ProtoMessage() {}

func (x *OneBusAwayFeedEntity) ProtoReflect() protoreflect.Message {
	mi := &file_gtfs_realtime_OneBusAway_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneBusAwayFeedEntity.ProtoReflect.Descriptor instead.
func (*OneBusAwayFeedEntity) Descriptor() ([]byte, []int) {
	return file_gtfs_realtime_OneBusAway_proto_rawDescGZIP(), []int{1}
}

func (x *OneBusAwayFeedEntity) GetSource() string {
	if x != nil && x.Source != nil {
		return *x.Source
	}
	return ""
}

type OneBusAwayTripUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Delay (in seconds) can be positive (meaning that the vehicle is late) or
	// negative (meaning that the vehicle is ahead of schedule). Delay of 0
	// means that the vehicle is exactly on time.
	//
	// # Deprecated in favor of TripUpdate.delay
	//
	// Deprecated: Marked as deprecated in gtfs-realtime-OneBusAway.proto.
	Delay *int32 `protobuf:"varint,1,opt,name=delay" json:"delay,omitempty"`
	// Moment at which the trip update was computed. In POSIX time
	// (i.e., number of seconds since January 1st 1970 00:00:00 UTC).
	//
	// # Deprecated in favor of TripUpdate.timestamp
	//
	// Deprecated: Marked as deprecated in gtfs-realtime-OneBusAway.proto.
	Timestamp *uint64 `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
	// trip headsign
	TripHeadsign *string `protobuf:"bytes,3,opt,name=tripHeadsign" json:"tripHeadsign,omitempty"`
	// trip direction
	TripDirection *string `protobuf:"bytes,4,opt,name=tripDirection" json:"tripDirection,omitempty"`
	// spooking aka zombie buses missing real-time but confirmed in revenue service
	IsEstimatedRealtime *bool `protobuf:"varint,5,opt,name=is_estimated_realtime,json=isEstimatedRealtime,def=0" json:"is_estimated_realtime,omitempty"`
}

// Default values for OneBusAwayTripUpdate fields.
const (
	Default_OneBusAwayTripUpdate_IsEstimatedRealtime = bool(false)
)

func (x *OneBusAwayTripUpdate) Reset() {
	*x = OneBusAwayTripUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gtfs_realtime_OneBusAway_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OneBusAwayTripUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneBusAwayTripUpdate) ProtoMessage() {}

func (x *OneBusAwayTripUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_gtfs_realtime_OneBusAway_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneBusAwayTripUpdate.ProtoReflect.Descriptor instead.
func (*OneBusAwayTripUpdate) Descriptor() ([]byte, []int) {
	return file_gtfs_realtime_OneBusAway_proto_rawDescGZIP(), []int{2}
}

// Deprecated: Marked as deprecated in gtfs-realtime-OneBusAway.proto.
func (x *OneBusAwayTripUpdate) GetDelay() int32 {
	if x != nil && x.Delay != nil {
		return *x.Delay
	}
	return 0
}

// Deprecated: Marked as deprecated in gtfs-realtime-OneBusAway.proto.
func (x *OneBusAwayTripUpdate) GetTimestamp() uint64 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

func (x *OneBusAwayTripUpdate) GetTripHeadsign() string {
	if x != nil && x.TripHeadsign != nil {
		return *x.TripHeadsign
	}
	return ""
}

func (x *OneBusAwayTripUpdate) GetTripDirection() string {
	if x != nil && x.TripDirection != nil {
		return *x.TripDirection
	}
	return ""
}

func (x *OneBusAwayTripUpdate) GetIsEstimatedRealtime() bool {
	if x != nil && x.IsEstimatedRealtime != nil {
		return *x.IsEstimatedRealtime
	}
	return Default_OneBusAwayTripUpdate_IsEstimatedRealtime
}

type OneBusAwayStopTimeUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StopHeadsign *string `protobuf:"bytes,1,opt,name=stopHeadsign" json:"stopHeadsign,omitempty"`
}

func (x *OneBusAwayStopTimeUpdate) Reset() {
	*x = OneBusAwayStopTimeUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gtfs_realtime_OneBusAway_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OneBusAwayStopTimeUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneBusAwayStopTimeUpdate) ProtoMessage() {}

func (x *OneBusAwayStopTimeUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_gtfs_realtime_OneBusAway_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneBusAwayStopTimeUpdate.ProtoReflect.Descriptor instead.
func (*OneBusAwayStopTimeUpdate) Descriptor() ([]byte, []int) {
	return file_gtfs_realtime_OneBusAway_proto_rawDescGZIP(), []int{3}
}

func (x *OneBusAwayStopTimeUpdate) GetStopHeadsign() string {
	if x != nil && x.StopHeadsign != nil {
		return *x.StopHeadsign
	}
	return ""
}

type OneBusAwayEntitySelector struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ElevatorId *string `protobuf:"bytes,1,opt,name=elevatorId" json:"elevatorId,omitempty"`
}

func (x *OneBusAwayEntitySelector) Reset() {
	*x = OneBusAwayEntitySelector{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gtfs_realtime_OneBusAway_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OneBusAwayEntitySelector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneBusAwayEntitySelector) ProtoMessage() {}

func (x *OneBusAwayEntitySelector) ProtoReflect() protoreflect.Message {
	mi := &file_gtfs_realtime_OneBusAway_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneBusAwayEntitySelector.ProtoReflect.Descriptor instead.
func (*OneBusAwayEntitySelector) Descriptor() ([]byte, []int) {
	return file_gtfs_realtime_OneBusAway_proto_rawDescGZIP(), []int{4}
}

func (x *OneBusAwayEntitySelector) GetElevatorId() string {
	if x != nil && x.ElevatorId != nil {
		return *x.ElevatorId
	}
	return ""
}

type OneBusAwayVehicleDescriptor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// list features of this vehicle, like kneeling, wifi, etc.
	VehicleFeature []string `protobuf:"bytes,1,rep,name=vehicleFeature" json:"vehicleFeature,omitempty"`
}

func (x *OneBusAwayVehicleDescriptor) Reset() {
	*x = OneBusAwayVehicleDescriptor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gtfs_realtime_OneBusAway_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OneBusAwayVehicleDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneBusAwayVehicleDescriptor) ProtoMessage() {}

func (x *OneBusAwayVehicleDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_gtfs_realtime_OneBusAway_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneBusAwayVehicleDescriptor.ProtoReflect.Descriptor instead.
func (*OneBusAwayVehicleDescriptor) Descriptor() ([]byte, []int) {
	return file_gtfs_realtime_OneBusAway_proto_rawDescGZIP(), []int{5}
}

func (x *OneBusAwayVehicleDescriptor) GetVehicleFeature() []string {
	if x != nil {
		return x.VehicleFeature
	}
	return nil
}

var file_gtfs_realtime_OneBusAway_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*FeedHeader)(nil),
		ExtensionType: (*OneBusAwayFeedHeader)(nil),
		Field:         1000,
		Name:          "transit_realtime.oba_feed_header",
		Tag:           "bytes,1000,opt,name=oba_feed_header",
		Filename:      "gtfs-realtime-OneBusAway.proto",
	},
	{
		ExtendedType:  (*FeedEntity)(nil),
		ExtensionType: (*OneBusAwayFeedEntity)(nil),
		Field:         1000,
		Name:          "transit_realtime.oba_feed_entity",
		Tag:           "bytes,1000,opt,name=oba_feed_entity",
		Filename:      "gtfs-realtime-OneBusAway.proto",
	},
	{
		ExtendedType:  (*TripUpdate)(nil),
		ExtensionType: (*OneBusAwayTripUpdate)(nil),
		Field:         1000,
		Name:          "transit_realtime.oba_trip_update",
		Tag:           "bytes,1000,opt,name=oba_trip_update",
		Filename:      "gtfs-realtime-OneBusAway.proto",
	},
	{
		ExtendedType:  (*TripUpdate_StopTimeUpdate)(nil),
		ExtensionType: (*OneBusAwayStopTimeUpdate)(nil),
		Field:         1000,
		Name:          "transit_realtime.oba_stop_time_update",
		Tag:           "bytes,1000,opt,name=oba_stop_time_update",
		Filename:      "gtfs-realtime-OneBusAway.proto",
	},
	{
		ExtendedType:  (*EntitySelector)(nil),
		ExtensionType: (*OneBusAwayEntitySelector)(nil),
		Field:         1000,
		Name:          "transit_realtime.oba_entity_selector",
		Tag:           "bytes,1000,opt,name=oba_entity_selector",
		Filename:      "gtfs-realtime-OneBusAway.proto",
	},
	{
		ExtendedType:  (*VehicleDescriptor)(nil),
		ExtensionType: (*OneBusAwayVehicleDescriptor)(nil),
		Field:         1000,
		Name:          "transit_realtime.oba_vehicle_descriptor",
		Tag:           "bytes,1000,opt,name=oba_vehicle_descriptor",
		Filename:      "gtfs-realtime-OneBusAway.proto",
	},
}

// Extension fields to FeedHeader.
var (
	// optional transit_realtime.OneBusAwayFeedHeader oba_feed_header = 1000;
	E_ObaFeedHeader = &file_gtfs_realtime_OneBusAway_proto_extTypes[0]
)

// Extension fields to FeedEntity.
var (
	// optional transit_realtime.OneBusAwayFeedEntity oba_feed_entity = 1000;
	E_ObaFeedEntity = &file_gtfs_realtime_OneBusAway_proto_extTypes[1]
)

// Extension fields to TripUpdate.
var (
	// optional transit_realtime.OneBusAwayTripUpdate oba_trip_update = 1000;
	E_ObaTripUpdate = &file_gtfs_realtime_OneBusAway_proto_extTypes[2]
)

// Extension fields to TripUpdate_StopTimeUpdate.
var (
	// optional transit_realtime.OneBusAwayStopTimeUpdate oba_stop_time_update = 1000;
	E_ObaStopTimeUpdate = &file_gtfs_realtime_OneBusAway_proto_extTypes[3]
)

// Extension fields to EntitySelector.
var (
	// optional transit_realtime.OneBusAwayEntitySelector oba_entity_selector = 1000;
	E_ObaEntitySelector = &file_gtfs_realtime_OneBusAway_proto_extTypes[4]
)

// Extension fields to VehicleDescriptor.
var (
	// optional transit_realtime.OneBusAwayVehicleDescriptor oba_vehicle_descriptor = 1000;
	E_ObaVehicleDescriptor = &file_gtfs_realtime_OneBusAway_proto_extTypes[5]
)

var File_gtfs_realtime_OneBusAway_proto protoreflect.FileDescriptor

var file_gtfs_realtime_OneBusAway_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x67, 0x74, 0x66, 0x73, 0x2d, 0x72, 0x65, 0x61, 0x6c, 0x74, 0x69, 0x6d, 0x65, 0x2d,
	0x4f, 0x6e, 0x65, 0x42, 0x75, 0x73, 0x41, 0x77, 0x61, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x10, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x5f, 0x72, 0x65, 0x61, 0x6c, 0x74, 0x69,
	0x6d, 0x65, 0x1a, 0x13, 0x67, 0x74, 0x66, 0x73, 0x2d, 0x72, 0x65, 0x61, 0x6c, 0x74, 0x69, 0x6d,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x89, 0x01, 0x0a, 0x14, 0x4f, 0x6e, 0x65, 0x42,
	0x75, 0x73, 0x41, 0x77, 0x61, 0x79, 0x46, 0x65, 0x65, 0x64, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x12, 0x2b, 0x0a, 0x11, 0x69, 0x6e, 0x63, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x5f,
	0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x10, 0x69, 0x6e, 0x63,
	0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x44, 0x0a,
	0x1e, 0x69, 0x6e, 0x63, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x5f, 0x68, 0x65, 0x61,
	0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x1c, 0x69, 0x6e, 0x63, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x61, 0x6c, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x72,
	0x76, 0x61, 0x6c, 0x22, 0x2e, 0x0a, 0x14, 0x4f, 0x6e, 0x65, 0x42, 0x75, 0x73, 0x41, 0x77, 0x61,
	0x79, 0x46, 0x65, 0x65, 0x64, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x22, 0xd7, 0x01, 0x0a, 0x14, 0x4f, 0x6e, 0x65, 0x42, 0x75, 0x73, 0x41, 0x77,
	0x61, 0x79, 0x54, 0x72, 0x69, 0x70, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x18, 0x0a, 0x05,
	0x64, 0x65, 0x6c, 0x61, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x42, 0x02, 0x18, 0x01, 0x52,
	0x05, 0x64, 0x65, 0x6c, 0x61, 0x79, 0x12, 0x20, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x42, 0x02, 0x18, 0x01, 0x52, 0x09, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x22, 0x0a, 0x0c, 0x74, 0x72, 0x69, 0x70,
	0x48, 0x65, 0x61, 0x64, 0x73, 0x69, 0x67, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x74, 0x72, 0x69, 0x70, 0x48, 0x65, 0x61, 0x64, 0x73, 0x69, 0x67, 0x6e, 0x12, 0x24, 0x0a, 0x0d,
	0x74, 0x72, 0x69, 0x70, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0d, 0x74, 0x72, 0x69, 0x70, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x39, 0x0a, 0x15, 0x69, 0x73, 0x5f, 0x65, 0x73, 0x74, 0x69, 0x6d, 0x61, 0x74,
	0x65, 0x64, 0x5f, 0x72, 0x65, 0x61, 0x6c, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x08, 0x3a, 0x05, 0x66, 0x61, 0x6c, 0x73, 0x65, 0x52, 0x13, 0x69, 0x73, 0x45, 0x73, 0x74, 0x69,
	0x6d, 0x61, 0x74, 0x65, 0x64, 0x52, 0x65, 0x61, 0x6c, 0x74, 0x69, 0x6d, 0x65, 0x22, 0x3e, 0x0a,
	0x18, 0x4f, 0x6e, 0x65, 0x42, 0x75, 0x73, 0x41, 0x77, 0x61, 0x79, 0x53, 0x74, 0x6f, 0x70, 0x54,
	0x69, 0x6d, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x73, 0x74, 0x6f,
	0x70, 0x48, 0x65, 0x61, 0x64, 0x73, 0x69, 0x67, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x73, 0x74, 0x6f, 0x70, 0x48, 0x65, 0x61, 0x64, 0x73, 0x69, 0x67, 0x6e, 0x22, 0x3a, 0x0a,
	0x18, 0x4f, 0x6e, 0x65, 0x42, 0x75, 0x73, 0x41, 0x77, 0x61, 0x79, 0x45, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x65, 0x6c, 0x65,
	0x76, 0x61, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x65,
	0x6c, 0x65, 0x76, 0x61, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x22, 0x45, 0x0a, 0x1b, 0x4f, 0x6e, 0x65,
	0x42, 0x75, 0x73, 0x41, 0x77, 0x61, 0x79, 0x56, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x44, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x12, 0x26, 0x0a, 0x0e, 0x76, 0x65, 0x68, 0x69,
	0x63, 0x6c, 0x65, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x0e, 0x76, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65,
	0x3a, 0x6d, 0x0a, 0x0f, 0x6f, 0x62, 0x61, 0x5f, 0x66, 0x65, 0x65, 0x64, 0x5f, 0x68, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x12, 0x1c, 0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x5f, 0x72, 0x65,
	0x61, 0x6c, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x46, 0x65, 0x65, 0x64, 0x48, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x18, 0xe8, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73,
	0x69, 0x74, 0x5f, 0x72, 0x65, 0x61, 0x6c, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x4f, 0x6e, 0x65, 0x42,
	0x75, 0x73, 0x41, 0x77, 0x61, 0x79, 0x46, 0x65, 0x65, 0x64, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x52, 0x0d, 0x6f, 0x62, 0x61, 0x46, 0x65, 0x65, 0x64, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x3a,
	0x6d, 0x0a, 0x0f, 0x6f, 0x62, 0x61, 0x5f, 0x66, 0x65, 0x65, 0x64, 0x5f, 0x65, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x12, 0x1c, 0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x5f, 0x72, 0x65, 0x61,
	0x6c, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x46, 0x65, 0x65, 0x64, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x18, 0xe8, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x69,
	0x74, 0x5f, 0x72, 0x65, 0x61, 0x6c, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x4f, 0x6e, 0x65, 0x42, 0x75,
	0x73, 0x41, 0x77, 0x61, 0x79, 0x46, 0x65, 0x65, 0x64, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52,
	0x0d, 0x6f, 0x62, 0x61, 0x46, 0x65, 0x65, 0x64, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x3a, 0x6d,
	0x0a, 0x0f, 0x6f, 0x62, 0x61, 0x5f, 0x74, 0x72, 0x69, 0x70, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x12, 0x1c, 0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x5f, 0x72, 0x65, 0x61, 0x6c,
	0x74, 0x69, 0x6d, 0x65, 0x2e, 0x54, 0x72, 0x69, 0x70, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x18,
	0xe8, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74,
	0x5f, 0x72, 0x65, 0x61, 0x6c, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x4f, 0x6e, 0x65, 0x42, 0x75, 0x73,
	0x41, 0x77, 0x61, 0x79, 0x54, 0x72, 0x69, 0x70, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x0d,
	0x6f, 0x62, 0x61, 0x54, 0x72, 0x69, 0x70, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x3a, 0x89, 0x01,
	0x0a, 0x14, 0x6f, 0x62, 0x61, 0x5f, 0x73, 0x74, 0x6f, 0x70, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x5f,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x2b, 0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74,
	0x5f, 0x72, 0x65, 0x61, 0x6c, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x54, 0x72, 0x69, 0x70, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x2e, 0x53, 0x74, 0x6f, 0x70, 0x54, 0x69, 0x6d, 0x65, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x18, 0xe8, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x74, 0x72, 0x61,
	0x6e, 0x73, 0x69, 0x74, 0x5f, 0x72, 0x65, 0x61, 0x6c, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x4f, 0x6e,
	0x65, 0x42, 0x75, 0x73, 0x41, 0x77, 0x61, 0x79, 0x53, 0x74, 0x6f, 0x70, 0x54, 0x69, 0x6d, 0x65,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x11, 0x6f, 0x62, 0x61, 0x53, 0x74, 0x6f, 0x70, 0x54,
	0x69, 0x6d, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x3a, 0x7d, 0x0a, 0x13, 0x6f, 0x62, 0x61,
	0x5f, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x12, 0x20, 0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x5f, 0x72, 0x65, 0x61, 0x6c, 0x74,
	0x69, 0x6d, 0x65, 0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74,
	0x6f, 0x72, 0x18, 0xe8, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x74, 0x72, 0x61, 0x6e,
	0x73, 0x69, 0x74, 0x5f, 0x72, 0x65, 0x61, 0x6c, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x4f, 0x6e, 0x65,
	0x42, 0x75, 0x73, 0x41, 0x77, 0x61, 0x79, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x53, 0x65, 0x6c,
	0x65, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x11, 0x6f, 0x62, 0x61, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x3a, 0x89, 0x01, 0x0a, 0x16, 0x6f, 0x62, 0x61,
	0x5f, 0x76, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x5f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x6f, 0x72, 0x12, 0x23, 0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x5f, 0x72, 0x65,
	0x61, 0x6c, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x56, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x44, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x18, 0xe8, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x2d, 0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x5f, 0x72, 0x65, 0x61, 0x6c, 0x74, 0x69,
	0x6d, 0x65, 0x2e, 0x4f, 0x6e, 0x65, 0x42, 0x75, 0x73, 0x41, 0x77, 0x61, 0x79, 0x56, 0x65, 0x68,
	0x69, 0x63, 0x6c, 0x65, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x52, 0x14,
	0x6f, 0x62, 0x61, 0x56, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x6f, 0x72, 0x42, 0x1d, 0x0a, 0x1b, 0x63, 0x6f, 0x6d, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x2e, 0x72, 0x65, 0x61, 0x6c, 0x74,
	0x69, 0x6d, 0x65,
}

var (
	file_gtfs_realtime_OneBusAway_proto_rawDescOnce sync.Once
	file_gtfs_realtime_OneBusAway_proto_rawDescData = file_gtfs_realtime_OneBusAway_proto_rawDesc
)

func file_gtfs_realtime_OneBusAway_proto_rawDescGZIP() []byte {
	file_gtfs_realtime_OneBusAway_proto_rawDescOnce.Do(func() {
		file_gtfs_realtime_OneBusAway_proto_rawDescData = protoimpl.X.CompressGZIP(file_gtfs_realtime_OneBusAway_proto_rawDescData)
	})
	return file_gtfs_realtime_OneBusAway_proto_rawDescData
}

var file_gtfs_realtime_OneBusAway_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_gtfs_realtime_OneBusAway_proto_goTypes = []interface{}{
	(*OneBusAwayFeedHeader)(nil),        // 0: transit_realtime.OneBusAwayFeedHeader
	(*OneBusAwayFeedEntity)(nil),        // 1: transit_realtime.OneBusAwayFeedEntity
	(*OneBusAwayTripUpdate)(nil),        // 2: transit_realtime.OneBusAwayTripUpdate
	(*OneBusAwayStopTimeUpdate)(nil),    // 3: transit_realtime.OneBusAwayStopTimeUpdate
	(*OneBusAwayEntitySelector)(nil),    // 4: transit_realtime.OneBusAwayEntitySelector
	(*OneBusAwayVehicleDescriptor)(nil), // 5: transit_realtime.OneBusAwayVehicleDescriptor
	(*FeedHeader)(nil),                  // 6: transit_realtime.FeedHeader
	(*FeedEntity)(nil),                  // 7: transit_realtime.FeedEntity
	(*TripUpdate)(nil),                  // 8: transit_realtime.TripUpdate
	(*TripUpdate_StopTimeUpdate)(nil),   // 9: transit_realtime.TripUpdate.StopTimeUpdate
	(*EntitySelector)(nil),              // 10: transit_realtime.EntitySelector
	(*VehicleDescriptor)(nil),           // 11: transit_realtime.VehicleDescriptor
}
var file_gtfs_realtime_OneBusAway_proto_depIdxs = []int32{
	6,  // 0: transit_realtime.oba_feed_header:extendee -> transit_realtime.FeedHeader
	7,  // 1: transit_realtime.oba_feed_entity:extendee -> transit_realtime.FeedEntity
	8,  // 2: transit_realtime.oba_trip_update:extendee -> transit_realtime.TripUpdate
	9,  // 3: transit_realtime.oba_stop_time_update:extendee -> transit_realtime.TripUpdate.StopTimeUpdate
	10, // 4: transit_realtime.oba_entity_selector:extendee -> transit_realtime.EntitySelector
	11, // 5: transit_realtime.oba_vehicle_descriptor:extendee -> transit_realtime.VehicleDescriptor
	0,  // 6: transit_realtime.oba_feed_header:type_name -> transit_realtime.OneBusAwayFeedHeader
	1,  // 7: transit_realtime.oba_feed_entity:type_name -> transit_realtime.OneBusAwayFeedEntity
	2,  // 8: transit_realtime.oba_trip_update:type_name -> transit_realtime.OneBusAwayTripUpdate
	3,  // 9: transit_realtime.oba_stop_time_update:type_name -> transit_realtime.OneBusAwayStopTimeUpdate
	4,  // 10: transit_realtime.oba_entity_selector:type_name -> transit_realtime.OneBusAwayEntitySelector
	5,  // 11: transit_realtime.oba_vehicle_descriptor:type_name -> transit_realtime.OneBusAwayVehicleDescriptor
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	6,  // [6:12] is the sub-list for extension type_name
	0,  // [0:6] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_gtfs_realtime_OneBusAway_proto_init() }
func file_gtfs_realtime_OneBusAway_proto_init() {
	if File_gtfs_realtime_OneBusAway_proto != nil {
		return
	}
	file_gtfs_realtime_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_gtfs_realtime_OneBusAway_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OneBusAwayFeedHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gtfs_realtime_OneBusAway_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OneBusAwayFeedEntity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gtfs_realtime_OneBusAway_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OneBusAwayTripUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gtfs_realtime_OneBusAway_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OneBusAwayStopTimeUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gtfs_realtime_OneBusAway_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OneBusAwayEntitySelector); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gtfs_realtime_OneBusAway_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OneBusAwayVehicleDescriptor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gtfs_realtime_OneBusAway_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 6,
			NumServices:   0,
		},
		GoTypes:           file_gtfs_realtime_OneBusAway_proto_goTypes,
		DependencyIndexes: file_gtfs_realtime_OneBusAway_proto_depIdxs,
		MessageInfos:      file_gtfs_realtime_OneBusAway_proto_msgTypes,
		ExtensionInfos:    file_gtfs_realtime_OneBusAway_proto_extTypes,
	}.Build()
	File_gtfs_realtime_OneBusAway_proto = out.File
	file_gtfs_realtime_OneBusAway_proto_rawDesc = nil
	file_gtfs_realtime_OneBusAway_proto_goTypes = nil
	file_gtfs_realtime_OneBusAway_proto_depIdxs = nil
}
